The-Whey/Capstone

README.md, src/Cart.js, src/index.js
If cart item only has 1 remove all button
does not show up, and minus button removes item
from cart/line item list.
=> Created increase and decrease buttons for cart items.

src/Cart.js, src/Orders.js, src/Product.js, src/Products.js, src/index.js
- Created a component for individual products.
- Created a URL route that displays individual products (above our stuff for now until we decide on a layout).
- Turned product name into a link in: Cart, Products, and Orders components.
=> Individual product

server/api/auth.js, server/db/index.js, src/Cart.js, src/Login.js, src/Orders.js, src/Product.js, src/Products.js, src/api/index.js, src/index.js
- Created a back end post method to create a new user ('/api/users')
- Created a function on front end to post to the back end method.
- Added a button underneath the login button to call that function using the pre-existing login inputs.
=> Create new user

server/index.js, src/api/index.js, src/index.js
Used setError to generate a state that we set to null. Modified login to include try/catch for errors. Used the try/catch to return error message to setError.
=> Credentials error handling

README.md, server/api/auth.js, server/db/auth.js, server/db/index.js, src/Admin.js, src/Login.js, src/api/index.js, src/index.js
- Created button backend support for a is_vip column in users table
- created button in admin page to set a user as a vip
- created button in admin page to remove vip status from user
- created api request to fetch individual users also.
=> Admin make user vip

README.md, server/api/lineItems.js, server/api/orders.js, server/db/cart.js, server/db/index.js, src/Admin.js, src/api/index.js, src/index.js
- created a backend and front end usestate that pulls all line items and all orders if user is admin.
- displays them on admin page.
=> Admin see all orders

server/api/products.js, src/Products.js
- Changed layout of products page a little bit.
- prices now display next to product.
=> Changed up the layout for products page and added prices listing

server/api/index.js, server/api/tags.js, server/db/index.js, server/db/tags.js, src/Products.js
Tags and product_tags both populate, but are not yet displayed.
=> Filter product tags

src/Products.js
Fixed an error caused by a previous merge on the products page.
=> deleted two lines that were causing an error

src/Cart.js, src/Orders.js
Completed this by filtering the total lineItems and once filtered summing them.
=> added total cart and total order values

package.json, server/api/products.js, server/db/index.js, server/db/products.js, src/Product.js, src/ReviewForm.js, src/api/index.js, src/index.js
=> New review form

index.html, src/Edit.js, src/Product.js, src/Products.js, src/index.js
- editing product is done through the individual page now instead of on the products page.
- editing product is no longer its own URL, its a useState on the product page.
=> Refactoring product edit

src/FilteredProducts.js, src/Products.js, src/index.js
Resolved search functionality and capitalization error. Seperated Order, cart, and products.
=> Search functionality

package.json, server/api/orders.js, server/db/auth.js, server/db/cart.js, server/db/index.js, src/Admin.js, src/Cart.js, src/Map.js, src/Orders.js, src/Product.js, src/api/index.js, src/index.js
- This is what was supposed to go in with location and maps
=> Restore deleted branch

server/api/tags.js, server/db/index.js, server/db/tags.js, src/Product.js, src/Products.js, src/ReviewForm.js, src/api/index.js, src/index.js
products can have tags added now
=> Adding tags

src/Products.js
/ added a button to show all items.
=> categories filters out any tags that aren't on any products

src/Products.js, src/Wishlist.js
Product images now act as a link to the product page
=> Image links

server/api/orders.js, server/db/cart.js, server/db/index.js, src/Product.js, src/Profile.js, src/api/index.js
At some point earlier I merged something that broke the webiste. I had an unpushed branch that has everything fixed, so this is correct branch.
=> Delete saved address

assets/styles.css, src/Cart.js, src/Orders.js, src/Product.js, src/Products.js, src/index.js
I broke out the css for links into it's own branch, while handling other bugs.
=> css styling for links only

assets/styles.css, package.json, src/Products.js
Not finished, but almost there.
=> working through flexbox errors on Products page

assets/styles.css, src/Products.js, src/index.js
updated links, header, nav bar, and logo css
=> updated links, header, nav bar, and logo css
